---
title: "Untitled"
author: "Andrea Arriaga-Madrigal"
date: "21/12/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

# sketchy::make_compendium("simulation_functional_diversity", path = "../", force = TRUE, format = compendiums$basic$skeleton)


library(pbapply)
library("BAT") #version 2.0.1 #update.packages("BAT") #<--- check out that you have the version 2.0.1
library("FD") #version 1.1-12
library("ggplot2")
library("gridExtra")
library("labdsv")
library("hypervolume") #version 2.0.11
library("psych")
library("StatMatch")
library("TPD") #version 1.1.0
library(extraDistr)

```


```{r}

traits <- read.table("./data/raw/mammola_cardoso_2020_BAT/traits.txt")[,c(1, 3, 4)]
communities <- read.table("./data/raw/mammola_cardoso_2020_BAT/comm.txt")
urb <- communities$Connection ## connection of the plot with the sourrounding matrix
communities <- communities[, 2:67]

communities_binary <- communities

communities_binary[communities_binary > 0] <- 1

species_by_community <- rowSums(communities_binary)
hist(species_by_community)

communities_counts <- communities

communities_counts[communities_counts == 0] <- NA
species_counts <- rowSums(communities_counts,na.rm = TRUE) / species_by_community


sp_median <- median(species_by_community)
sp_sd <- sd(species_by_community)
abun_median <- median(species_counts)
abun_sd <- sd(species_counts)

sim_community <- function(sp_median, sp_sd, abun_median, abun_sd, sp_names) {
  
  # simulate number of species  
  sp_num <- rdnorm(n = 1, mean = sp_median, sd = sp_sd)
  
  if (sp_num > length(sp_names))
    sp_num <- length(sp_names)
  
  if (sp_num < 1)
    sp_num <- 1
  
  species <- sample(sp_names, size = sp_num)
  
  # simulate abundances
  abundances <- rdnorm(n = length(species), mean = abun_median, sd = abun_sd)
  
  abundances[abundances < 1] <- 1

  present_sp <- data.frame(species = species, abundances = abundances)
  
  absent_sp <- data.frame(species = sp_names[!sp_names %in% species], abundances = 0)

  out_df <- rbind(present_sp, absent_sp)
    
  out_df <- out_df[order(out_df$species), -1]
  
  return(out_df)
}


sim_community(sp_median = sp_median, sp_sd =  sp_sd, abun_median = abun_median, abun_sd = abun_sd, sp_names = rownames(traits)) 

sim_comms_l <- replicate(n = 60, expr = {
  
  sim_community(sp_median = sp_median, sp_sd =  sp_sd, abun_median = abun_median, abun_sd = abun_sd, sp_names = rownames(traits)) 
}, simplify = FALSE)


sim_comms <- do.call(rbind, sim_comms_l)
colnames(sim_comms) <- sort(rownames(traits))
rownames(sim_comms) <- paste0("site-", 1:nrow(sim_comms))

colSums(sim_comms)

## Calculating the functional alpha diversity of each plot using the kernel.alpha function


seq(1, 51, 10)


vol_bat <- kernel.alpha(comm = sim_comms[, , drop = FALSE], trait = traits, abund = TRUE, method = "gaussian", return.hv = TRUE) 

as.numeric(vol_bat[[1]])
vol_bat[[2]]

```

